# Generated by Django 2.2.3 on 2019-07-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Títutlo')),
                ('desc', models.TextField(verbose_name='Descrição')),
                ('day', models.DateField(verbose_name='Dia')),
                ('isAllDay', models.BooleanField(verbose_name='É o dia inteiro?')),
                ('start', models.TimeField(verbose_name='Horário de começo')),
                ('end', models.TimeField(verbose_name='Horário de término')),
                ('link', models.URLField(blank=True, verbose_name='link')),
            ],
        ),
    ]
