# Generated by Django 2.2.3 on 2019-07-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20190725_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='link',
        ),
        migrations.AddField(
            model_name='evento',
            name='show_img',
            field=models.ImageField(default='CADir_logo.png', upload_to='', verbose_name='show_img'),
        ),
    ]
