# Generated by Django 2.2.3 on 2019-07-25 22:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20190725_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='day',
        ),
        migrations.AddField(
            model_name='evento',
            name='end_day',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Dia em que o Evento Acaba'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='start_day',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Dia em que o Evento começa'),
            preserve_default=False,
        ),
    ]
