# Generated by Django 2.1.1 on 2019-07-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='logo',
            field=models.ImageField(upload_to='programas_logo', verbose_name='logo'),
        ),
    ]
