# Generated by Django 2.1.1 on 2019-07-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0002_auto_20190710_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='site',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='programa',
            name='tipo',
            field=models.CharField(choices=[('ATL', 'Atlética'), ('EJ', 'Empresa Junior'), ('GE', 'Grupo de extensão'), ('OUT', 'Outros')], default='OUT', max_length=3, verbose_name='tipo'),
        ),
    ]
