# Generated by Django 2.2.1 on 2019-07-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0003_auto_20190710_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='show_img',
            field=models.ImageField(default='martelo.jpg', upload_to='programas_show_img', verbose_name='show_img'),
        ),
    ]
