# Generated by Django 2.1.1 on 2019-07-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0004_programa_show_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
