# Generated by Django 2.1.1 on 2019-07-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0006_auto_20190716_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='tipo',
            field=models.CharField(choices=[('ATL', 'Atlética'), ('EJ', 'Empresa Júnior'), ('GE', 'Grupos de extensão'), ('OUT', 'Outros')], default='OUT', max_length=3, verbose_name='tipo'),
        ),
    ]
