# Generated by Django 2.2.3 on 2019-07-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0008_remove_programa_show_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='show_img',
            field=models.ImageField(default='martelo.jpg', upload_to='programas_show_img', verbose_name='show_img'),
        ),
    ]
