# Generated by Django 2.2.3 on 2019-08-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0009_programa_show_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='audio',
            field=models.FileField(blank=True, upload_to='audio_programas'),
        ),
    ]
