# Generated by Django 2.2.3 on 2019-07-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='', verbose_name='Arquivo'),
        ),
        migrations.AddField(
            model_name='guia',
            name='nome',
            field=models.CharField(default='', max_length=60, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='guia',
            name='link',
            field=models.URLField(blank=True, verbose_name='Link'),
        ),
    ]
