# Generated by Django 2.2.3 on 2019-07-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0003_auto_20190729_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='file',
            field=models.FileField(blank=True, upload_to='guias_pdf', verbose_name='Arquivo'),
        ),
    ]
