# Generated by Django 2.2.3 on 2019-08-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0004_auto_20190729_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='desc',
            field=models.TextField(default='Guia CADir UnB', verbose_name='Descrição'),
        ),
    ]
