# Generated by Django 2.2.3 on 2019-08-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0005_guia_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='duracao',
            field=models.IntegerField(default=30, help_text='Colocar a duração em minutos', verbose_name='Duração de leitura'),
        ),
    ]
