# Generated by Django 2.2.3 on 2019-08-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0003_auto_20190729_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextoHistorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(help_text='Texto no qual se encontra no ver mais do histórico do CADir', verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Texto do histórico do CADir',
                'verbose_name_plural': 'Texto do histórico do CADir',
            },
        ),
    ]
