# Generated by Django 2.2.3 on 2019-08-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0005_prestacaodecontas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome que aparecerá no site(Institucional)', max_length=60, verbose_name='Nome')),
                ('file', models.FileField(upload_to='atas_pdf', verbose_name='Arquivo')),
            ],
            options={
                'verbose_name': 'Ata',
                'verbose_name_plural': 'Atas',
            },
        ),
    ]
