# Generated by Django 2.2.3 on 2019-08-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0006_atas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(help_text='Nome da gestão correspondente', max_length=50, verbose_name='Nome')),
                ('periodo', models.TextField(help_text='Período pelo qual a gestão ficou responsável pelo CADir (ex: 1998 - 1999', max_length=12, verbose_name='Período da Gestão')),
                ('logo', models.ImageField(help_text='Logo da gestão correspondente', upload_to='', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logos',
            },
        ),
    ]
