# Generated by Django 2.2.3 on 2019-08-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0007_logos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logos',
            name='periodo',
        ),
        migrations.AddField(
            model_name='logos',
            name='ano_final',
            field=models.TextField(default='0000', help_text='Ano em que a gestão encerrou o mandato', max_length=4, verbose_name='Ano de término'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logos',
            name='ano_inicial',
            field=models.TextField(default='0000', help_text='Ano em que a gestão iniciou o mandato', max_length=4, verbose_name='Ano de início'),
            preserve_default=False,
        ),
    ]
