# Generated by Django 2.2.3 on 2019-08-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0008_auto_20190810_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logos',
            name='ano_final',
            field=models.CharField(help_text='Ano em que a gestão encerrou o mandato', max_length=4, verbose_name='Ano de término'),
        ),
        migrations.AlterField(
            model_name='logos',
            name='ano_inicial',
            field=models.CharField(help_text='Ano em que a gestão iniciou o mandato', max_length=4, verbose_name='Ano de início'),
        ),
        migrations.AlterField(
            model_name='logos',
            name='nome',
            field=models.CharField(help_text='Nome da gestão correspondente', max_length=50, verbose_name='Nome'),
        ),
    ]
