# Generated by Django 2.2.3 on 2019-08-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0009_auto_20190810_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estatuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome que aparecerá no site(Institucional)', max_length=60, verbose_name='Nome')),
                ('file', models.FileField(upload_to='estato', verbose_name='Arquivo')),
            ],
            options={
                'verbose_name': 'Estatuto',
                'verbose_name_plural': 'Estatutos',
            },
        ),
    ]
